# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B"]

# Never enforce `E501` (line length violations).
ignore = ["E501", "B905"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

[per-file-ignores]
"__init__.py" = ["E501"]
