alias ll='ls -lh --color=auto'
alias lla='ls -lha --color=auto'
alias ber='bundle exec rake'
alias be='bundle exec'
alias sp='bundle exec rspec'
alias rdb='bundle exec rails dbconsole'
alias rs='bundle exec rails server'
alias rc='bundle exec rails console'
alias r='bundle exec rails'
alias i='sudo apt-get install'
alias aptisearch='sudo aptitude search'
alias aptcp='sudo apt-cache policy'
alias up='sudo apt-get update && sudo apt-get upgrade'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias svim='sudo vim'
alias ..='cd ../'
alias ...='cd ../../'
alias vimod='vim -p $(git diff --name-only | uniq)'
