#!/usr/bin/env bash

# set -o errexit, exit when a command fails
# add || true to commands that you allow to fail
set -e

# set -o nounset, exit when script tries to use undeclared variables
set -u

# exit status of the last command that threw a non-zero exit code is returned
set -o pipefail

# set -o xtrace, trace what gets executed
[[ "${TRACE:-}" ]] && set -x


main () {
  dir=$(pwd)

  # bash
  ln -fs $dir/bash/bashrc ~/.bashrc
  ln -fs $dir/bash/bash_profile ~/.bash_profile
  ln -fs $dir/bash/bash_aliases ~/.bash_aliases

  # xmonad
  ln -fs $dir/xmonad/xmonad.hs ~/.xmonad/xmonad.hs
  ln -fs $dir/xmonad/xmobar-volume ~/.xmonad/xmobar-volume
  ln -fs $dir/xmonad/stalonetrayrc-single ~/.xmonad/stalonetrayrc-single

  # git
  ln -fs $dir/git/gitconfig ~/.gitconfig

  # vim
  ln -fs $dir/vim ~/.vim
  ln -fs $dir/vim/vimrc ~/.vimrc

  # tmux
  ln -fs $dir/tmux/tmux.conf ~/.tmux.conf
  ln -fs $dir/tmux/tmuxline.conf ~/.tmuxline.conf

  # urxvt
  ln -fs $dir/Xdefaults ~/.Xdefaults
  ln -fs $dir/xsession ~/.xsession

  ln -fs $dir/curlrc ~/.curlrc
  ln -fs $dir/tigrc ~/.tigrc

  trap - EXIT
}

main "$@"
