# General aliases
alias ls='ls -Glahp'
alias grep='grep --color'
alias fgrep='fgrep --color'

# Directory shortcuts
alias btr='cd ~/Workspace/bartendr'
alias fut='cd ~/Workspace/futurae'
alias wp='cd ~/Workspace'
alias x11='cd ~/Google\ Drive/Workspace/x11-squad'

# youtube-dl
alias ut='youtube-dl'
alias utmp3='youtube-dl -x --audio-format mp3 --audio-quality 0'

# virtualenv
venv_activate() {
    source "$1/bin/activate"
}
alias venv=venv_activate

# docker
alias doc='docker-compose'
alias dex='docker exec -it'

# Futurae
alias dbreset='doc down && ./tasks/docker/db_bootstrap.sh && ./tasks/docker/app_bootstrap.sh'

# Fun
alias coin='coinmon -c eur -H -f btc,eth,xrp,trx,dash,bch,ltc,icx,xmr'
