# General aliases
alias ls='ls -Glahp'
alias grep='grep --color'
alias fgrep='fgrep --color'

# Directory shortcuts
alias btr='cd ~/Workspace/bartendr'
alias x11='cd ~/Google\ Drive/Workspace/x11-squad'

# youtube-dl
alias ut='youtube-dl'
alias utmp3='youtube-dl -x --audio-format mp3 --audio-quality 0'
