" Auto completion settings
filetype on
filetype plugin on
filetype indent on

" Misc settings
set showcmd
syntax enable
colorscheme elflord
"set cursorline

set autoindent
set expandtab
set smarttab
set shiftwidth=4
set softtabstop=4
set number
set nocompatible
set incsearch
set hlsearch
set backspace=indent,eol,start
set showtabline=2
set colorcolumn=80
highlight ColorColumn ctermbg=DarkGrey
"set cursorline
"highlight Cursorline cterm=NONE ctermbg=darkgrey ctermfg=white

"Show trailing whitespace
highlight ExtraWhitespace ctermbg=darkblue guibg=#344011
autocmd BufEnter * exe ':2match ExtraWhitespace /\s\+$\| \+\ze\t\|\t\+\ze /'

" Pathogen
execute pathogen#infect()
filetype plugin indent on

" Vim. Live it.
noremap <up> <nop>
noremap <down> <nop>
noremap <left> <nop>
noremap <right> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
inoremap <up> <nop>
vnoremap <up> <nop>
vnoremap <down> <nop>
vnoremap <left> <nop>
vnoremap <right> <nop>

" Highlight all occurences of current word without moving
nnoremap <C-b> *``

" Tab switching alternatives to gt/gT
nnoremap <C-l> :tabnext<CR>
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-t> :tabnew 
inoremap <C-l> <Esc>:tabnext<CR>i
inoremap <C-h> <Esc>:tabprevious<CR>i
inoremap <C-t> <Esc>:tabnew 

"Ctrl+R replaces all occurences of selected text in visual mode, Ctrl+Shift+R
"only the selected one
vnoremap <C-r> "hy:%s/<C-r>h//g<left><left>

" Auto-complete brackets
"inoremap {      {}<Left>
inoremap {<CR>  {<CR>}<Esc>O
inoremap {{     {
inoremap {}     {}

" Insert new line at the cursor without entering insert mode
nnoremap <S-Enter> i<CR><Esc>

" NERDTree
let mapleader = ","
nmap <leader>d :NERDTree<cr>

""""""""
" Perl "
""""""""

" perltidy
command -range=% -nargs=* Tidy <line1>,<line2>!C:/Personal/Programs/cygwin/home/rinis/bin/Perl-Tidy-20140328/perltidy

"run :Tidy on entire buffer and return cursor to (approximate) original position"
fun DoTidy()
    let l = line(".")
    let c = col(".")
    :Tidy
    call cursor(l, c)
endfun

"shortcut for normal mode to run on entire buffer then return to current line"
au Filetype perl nmap <C-S-f> :call DoTidy()<CR>

"shortcut for visual mode to run on the the current visual selection"
au Filetype perl vmap <C-S-f> :Tidy<CR>

"CtrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim
nmap <C-p> :CtrlP<CR>

"Python -- flake8
autocmd BufWritePost *.py call Flake8()
let g:flake8_show_quickfix=0
let g:flake8_show_in_file=1
"use colors defined in the colorscheme
highlight link Flake8_Error      Error
highlight link Flake8_Warning    WarningMsg
highlight link Flake8_Complexity WarningMsg
highlight link Flake8_Naming     WarningMsg
highlight link Flake8_PyFlake    WarningMsg

" vim-airline
let g:airline#extensions#tabline#enabled = 1
set laststatus=2
