#! /bin/bash

USER=pmichail
MASTER_BRANCH=master

function usage() {
  cat << EOS
    Usage:
      gbranch -j <jira-ticket>

    Examples:
      gbranch -j SDK-100
EOS
  exit 1;
}

while getopts ":j:h" o; do
    case "${o}" in
        j)
            JIRA_TICKET_DESCRIPTOR=${OPTARG}
            ;;
        h)
            usage
            ;;
    esac
done

shift $((OPTIND-1))

if [ -z "${JIRA_TICKET_DESCRIPTOR}" ]; then
    usage
fi

source ~/.apparatus/scripts/profile/jira

JIRA_TICKET=$(ticket_key $JIRA_TICKET_DESCRIPTOR)
JIRA_PROJECT=$(ticket_project $JIRA_TICKET_DESCRIPTOR)
BRANCH=${USER}_${JIRA_TICKET}
BRANCH_EXISTS=$(git branch -a | grep ${BRANCH})

if [ ! -z "$(git status --porcelain)" ]; then
  echo please commit your changes first
  exit
fi

if [ ! -z "${BRANCH_EXISTS}" ]; then
    echo branch $BRANCH exists
    exit
fi

SUMMARY=$(jira issue list --plain --no-headers --columns "key,summary" --project ${JIRA_PROJECT} -q"key=${JIRA_TICKET}" | awk -F '\t' '{ print $2;}')

if [ -z "${SUMMARY}" ]; then
    echo Cannot find jira ticket $JIRA_TICKET
    exit
fi

git checkout ${MASTER_BRANCH}
git pull
git checkout -b ${BRANCH}
git commit --allow-empty -m "${SUMMARY}"
git push -u origin ${BRANCH}
