#!/bin/bash
set -e

read -r FULLPATH DIRECTORY FILENAME EXTENSION <<<$(get_path_info $1)

EXIF_DATE=$(exiftool -T -DateTimeOriginal "$FULLPATH")

if [ "$EXIF_DATE" != "-" ];
then
  TIMESTAMP=$(date -j -f "%Y:%m:%d %H:%M:%S" "${EXIF_DATE}" +%s)
  date -r $TIMESTAMP "+%Y%m%d"
fi
