#!/bin/bash
set -e

function relative_path() {
  python -c "import os,sys;print(os.path.relpath(*(sys.argv[1:])))" "$@";
}

function absolute() {
  echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
}

function get_diff() {
  comm -3 <(</dev/null exiftool "$1") <(</dev/null exiftool "$2")
}

function move_file() {
  local FULLPATH=$(realpath "$1")
  local FILENAME=$(basename "$FULLPATH")
  local DIR=$(realpath "$2")
  local OUTPUT_PATH="$DIR"/"$FILENAME"

  if [[ -f "$OUTPUT_PATH" ]]
  then
    echo "$OUTPUT_PATH" exists...
    get_diff "$FULLPATH" "$OUTPUT_PATH"
    read -p "Are you sure? " -n 1 -r
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
      echo Moving "$FILENAME" to "$OUTPUT_PATH"
      mv "$FILENAME" "$OUTPUT_PATH"
    else
      echo Aborted
    fi
  else
    echo Moving "$FILENAME" to "$OUTPUT_PATH"
  fi
}

function move_folder_contents() {
  find "$(realpath "$1")" -type f -not -path '*/.*' -exec mv_conditional {} "$2" \;
}

if [[ -d "$1" ]]
then
  move_folder_contents "$1" "$2"
elif [[ -f "$1" ]]
then
  move_file "$1" "$2"
else
  echo "Expecting a directory as input"
  exit -1
fi
