#! /bin/bash

function usage() {
  cat << EOS
    Usage:
      reflog -d <days-ago>

    Examples:
      reflog -d 1
EOS
  exit 1;
}

while getopts ":d:h" o; do case "${o}" in d) DAYS_AGO=${OPTARG} ;; h) usage ;; esac done

shift $((OPTIND-1))
if [ -z "${DAYS_AGO}" ]; then usage; fi

source ~/.apparatus/scripts/profile/git
gref-json-list $DAYS_AGO \
  | ~/.apparatus/scripts/parse-intervals.py
