#!/usr/bin/env bash
#xrandr --auto --output DP1 --mode 1920x1200 --left-of eDP1 --primary
xrandr --auto --output DP1 --mode 1920x1080 --right-of eDP1 --primary
xrandr --auto --output eDP1 --left-of DP1
kill $(pgrep trayer)
~/.bin/tray &
feh --bg-fill ~/Downloads/wallpapers/a_kombi_bus-wallpaper-1920x1080.jpg
