#!/usr/bin/env bash

dex () {
    docker exec -it -e COLUMNS=$COLUMNS -e LINES=$LINES "$1" $2
}

dlg () {
    docker logs "$1" --follow
}

drc () {
    docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
}

drv () {
    docker volume prune
}

removecontainers() {
    docker stop $(docker ps -aq)
    docker rm $(docker ps -aq)
}

docker_kill_all() {
    removecontainers
    docker network prune -f
    docker volume rm $(docker volume ls --filter dangling=true -q)
}

armageddon() {
    removecontainers
    docker network prune -f
    docker rmi -f $(docker images --filter dangling=true -qa)
    docker volume rm $(docker volume ls --filter dangling=true -q)
    docker rmi -f $(docker images -qa)
}
