#!/usr/bin/env bash

group_tickets() {
  args="$@"
  # jira issue list --plain --no-truncate --columns type,key,status,priority,created,updated,summary,assignee \
  #   --project BT -q"key IN (BT-1850)"
  echo $args | awk -F '\t' -f $HOME/.apparatus/scripts/awk/parse-tickets.awk
}

jget() {
  group_tickets $@ |
  while IFS= read -r ROW; do
    project=$(echo $ROW | awk '{print $1}')
    tickets=$(echo $ROW | awk '{print $2}')

    jira issue list --no-headers --plain --no-truncate --columns type,key,status,priority,created,updated,summary,assignee \
      --project ${project} -q"key IN (${tickets})" \
      | awk -F '\t' -f $HOME/.apparatus/scripts/awk/json-tickets.awk \
      | tr -s " " | jq -c
  done
}
