#!/usr/bin/env bash

timew_slurp() {
  while IFS=$"\n" read -r c; do
    cmd=$(echo timew track $c)
    echo $cmd
    eval $cmd
  done
}

timew_purge() {
  timew ids :all | head -n 1 |
  while IFS=$"\n" read -r c; do
    cmd=$(echo timew delete $c)
    echo $cmd
    eval $cmd
  done
}

timew_from_git() {
  if [ -z $1 ]; then
    echo "Usage:\n\ttimew_from_git [days_back]"
    return 1
  fi
  gref $1 | jq -L$HOME/.apparatus/scripts/jq -rf $HOME/.apparatus/scripts/jq/gj2tw.jq
}

timew_track_from_git() {
  if [ -z $1 ]; then
    echo "Usage:\n\ttimew_track_from_git [days_back]"
    return 1
  fi
  timew_from_git $1 | timew_slurp
}

timew_all() {
  timew json :all
}

timew_summary() {
  timew json :all
}

timew_annotate_from_jira() {
  tickets=$(timew tickets :all | xargs)
  json_tickets $tickets
}
