#!/usr/bin/env bash

read -r -d '' jq_dump_script <<- EOM
  .intervals
  | map(
    "from \(.start) to \(.end)" as \$range
    | [
      "timew track \(\$range) \(.tags | map("\"\(.)\"") | join(" ") )",
      if .annotation != null then "timew annotate_by_range \(\$range) \"\(.annotation)\"" else empty end
    ]
  ) | flatten []
EOM

$(dirname "$0")/json | jq -r "$jq_dump_script"
