#!/usr/bin/env bash

(
INTERVAL_GROUPING_FILTER=get_interval_month INTERVAL_SORTING_FILTER=".timestamps.startedAt" INTERVAL_PERIOD_FORMAT_FILTER='(.timestamps.startedAt | strftime("%B %Y"))' \
  $(dirname "$0")/billing \
  | jq -L$HOME/.apparatus/scripts/jq \
  'include "lib/timewarrior"; invoice_data_from_env'
 )
