#!/usr/bin/env bash

input=$(tee)

read -r -d '' jq_read_config_script <<- EOM
  split("\n")
  | map(
    select(. != "")
    | split(":")
    | { key: .[0], value: (.[1] | gsub("^ ";"")) }
  )
  | { config: from_entries }
EOM

read -r -d '' jq_parse_intervals_script <<- EOM
  {
    intervals: map(
      { id, start, end: .end, tags, annotation }
    )
  }
EOM


echo "$input" | (
  # read configuration (up to empty line)
  while read l; do
    [[ ! -z "$l" ]] || break && echo $l;
  done \
  | jq -Rs "$jq_read_config_script";
  # read intervals (rest of input)
  while read l; do
    echo $l;
  done \
  | jq "$jq_parse_intervals_script"
) | jq -s add
