#!/usr/bin/env bash

set -e

input=$(tee)
items=$(
  echo "$input" | ( \
    INTERVAL_GROUPING_FILTER='get_interval_category' \
    INTERVAL_SORTING_FILTER='(.tickets | first | .number), .timestamps.startedAt, .group' \
    $(dirname "$0")/billing  \
  ) | jq '{ items: . }'
)
tickets=$(echo "$input" | ($(dirname "$0")/jiras) | jq '{ tickets: . }')
all_data=$((echo "$items"; echo "$tickets") | jq -s add)

data=$(
  echo $all_data | jq -L$HOME/.apparatus/scripts/jq -cf $HOME/.apparatus/scripts/jq/invoice_data_from_env.jq
)

if [ "$FORMAT" = "html" ]; then
  tera --template $HOME/.apparatus/jinja/timesheet.template.html --stdin < <(echo $data)
else
  echo $data | jq '.'
fi
