#!/usr/bin/env bash

(
  INTERVAL_GROUPING_FILTER=get_interval_category INTERVAL_SORTING_FILTER="(.tickets | first | .number), .timestamps.startedAt, .group" \
  $(dirname "$0")/billing \
  | jq -L$HOME/.apparatus/scripts/jq \
  'include "lib/timewarrior"; invoice_data_from_env'
 )
