#!/usr/bin/env bash

set -e

input=$(tee)
data=$(
  echo "$input" | ( \
    ANNOTATE_FROM_JIRA=true \
    INTERVAL_GROUPING_FILTER='get_interval_category' \
    INTERVAL_SORTING_FILTER='(.tickets | first | .number), .timestamps.startedAt, .group' \
    $(dirname "$0")/billing | jq -L$HOME/.apparatus/scripts/jq -cf $HOME/.apparatus/scripts/jq/invoice_data_from_env.jq
  )
)

if [ "$FORMAT" = "html" ]; then
  tera --template $HOME/.apparatus/jinja/timesheet.template.html --stdin < <(echo $data)
else
  echo $data | jq '.'
fi
