# Configure bash prompt
source ~/.bash_prompt

# Aliases
source ~/.bash_aliases

# Plugins and Extras
source ~/.bash_extras

# Display archey
archey -o

# PATH definitions
export PATH="$HOME/.rbenv/bin:/usr/local/sbin:$PATH"
export EDITOR="vim"

eval "$(rbenv init -)"

# Futurae
export PATH="$GOPATH/bin:$PATH"
export FUTURAE_CI_TOKEN=
export FUTURAE="/Users/ilias/Workspace/futurae"

# direnv
eval "$(direnv hook bash)"

[[ -s "/Users/ilias/.gvm/scripts/gvm" ]] && source "/Users/ilias/.gvm/scripts/gvm"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
