# Configure bash prompt
source ~/.bash_prompt

# Aliases
source ~/.bash_aliases

# Plugins and Extras
source ~/.bash_extras

# Display archey
archey

# PATH definitions
export PATH="/usr/local/sbin:$PATH"

# GOPATH
export GOPATH="/Users/ilias/Workspace/futurae/webapp/"
eval $(/usr/libexec/path_helper -s)

# direnv
eval "$(direnv hook bash)"
